#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AzureGui.Resource", IsApplication=true)]

namespace AzureGui
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::AzureGui.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::AzureGui.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::AzureGui.Resource.String.ApplicationName;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sqlDatabase = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int actionMenuView1 = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int action_back = 2131034127;
			
			// aapt resource value: 0x7f050019
			public const int action_delete = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int action_favourites = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int action_name = 2131034138;
			
			// aapt resource value: 0x7f05000e
			public const int action_refresh = 2131034126;
			
			// aapt resource value: 0x7f05001d
			public const int action_region = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int action_resourceGroup = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int action_test = 2131034117;
			
			// aapt resource value: 0x7f05001c
			public const int action_type = 2131034140;
			
			// aapt resource value: 0x7f050024
			public const int agentWebView = 2131034148;
			
			// aapt resource value: 0x7f050000
			public const int appServicePlanImage = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int appServicePlanListButton = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int appServicePlanLocation = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int appServicePlanName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int appServiceResourceGroupName = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int appServiceSubscriptionName = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int button1 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int button2 = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int loginButton = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int logoutButton = 2131034120;
			
			// aapt resource value: 0x7f050016
			public const int optionsButton = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int resourceActionButton = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int resourceGroupName = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int resourceImage = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int resourceList = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int resourceName = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int searchTextView = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int sortButton = 2131034133;
			
			// aapt resource value: 0x7f050023
			public const int sqlDatabaseActionButton = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int sqlDatabaseIsActive = 2131034142;
			
			// aapt resource value: 0x7f05000a
			public const int sqlDatabaseListButton = 2131034122;
			
			// aapt resource value: 0x7f05001f
			public const int sqlDatabaseLocation = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int sqlServerImage = 2131034144;
			
			// aapt resource value: 0x7f050009
			public const int sqlServerListButton = 2131034121;
			
			// aapt resource value: 0x7f050021
			public const int sqlServerName = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int sqlServerResourceGroupName = 2131034146;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppServicePlan = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int databasePopupMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int popupMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int resource = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ResourceGroup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int resourcePopupMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sortByMenu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SqlDatabase = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SqlServer = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WebAuthenticationBroker = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
